export enum Editions {
  ENTERPRISE = 'ENTERPRISE',
  TEAM = 'TEAM',
  FREE = 'FREE',
  COMMUNITY = 'COMMUNITY'
}

export enum ModuleLicenseType {
  TRIAL = 'TRIAL',
  PAID = 'PAID',
  FREE = 'FREE',
  COMMUNITY = 'COMMUNITY'
}

export enum RestrictionType {
  AVAILABILITY = 'AVAILABILITY',
  STATIC_LIMIT = 'STATIC_LIMIT',
  RATE_LIMIT = 'RATE_LIMIT',
  CUSTOM = 'CUSTOM'
}

export enum SUBSCRIPTION_TAB_NAMES {
  OVERVIEW = 'OVERVIEW',
  PLANS = 'PLANS',
  BILLING = 'BILLING'
}

export enum PLAN_UNIT {
  YEARLY = 'YEARLY',
  MONTHLY = 'MONTHLY'
}

export enum SERVICES_CARDS {
  CURRENT_USAGE_CARD = 'CURRENT_USAGE_CARD',
  ACTUAL_USAGE_CARD = 'ACTUAL_USAGE_CARD',
  OVERUSE_USAGE_CARD = 'OVERUSE_USAGE_CARD',
  RECOMMENDATION_USAGE_CARD = 'RECOMMENDATION_USAGE_CARD'
}

export enum LOOKUP_KEYS {
  CD_ENTERPRISE_SERVICE_MONTHLY = 'CD_ENTERPRISE_SERVICE_MONTHLY',
  CD_ENTERPRISE_SERVICE_YEARLY = 'CD_ENTERPRISE_SERVICE_YEARLY',
  CD_ENTERPRISE_PREMIUM_SUPPORT_MONTHLY = 'CD_ENTERPRISE_PREMIUM_SUPPORT_MONTHLY',
  CD_ENTERPRISE_PREMIUM_SUPPORT_YEARLY = 'CD_ENTERPRISE_PREMIUM_SUPPORT_YEARLY',
  CI_ENTERPRISE_DEVELOPERS_MONTHLY = 'CI_ENTERPRISE_DEVELOPERS_MONTHLY',
  CI_ENTERPRISE_DEVELOPERS_YEARLY = 'CI_ENTERPRISE_DEVELOPERS_YEARLY',
  CI_TEAM_DEVELOPERS_MONTHLY = 'CI_TEAM_DEVELOPERS_MONTHLY',
  CI_TEAM_DEVELOPERS_YEARLY = 'CI_TEAM_DEVELOPERS_YEARLY'
}
