export enum Editions {
  ENTERPRISE = 'ENTERPRISE',
  TEAM = 'TEAM',
  FREE = 'FREE',
  COMMUNITY = 'COMMUNITY'
}

export enum ModuleLicenseType {
  TRIAL = 'TRIAL',
  PAID = 'PAID',
  FREE = 'FREE',
  COMMUNITY = 'COMMUNITY'
}

export enum RestrictionType {
  AVAILABILITY = 'AVAILABILITY',
  STATIC_LIMIT = 'STATIC_LIMIT',
  RATE_LIMIT = 'RATE_LIMIT',
  CUSTOM = 'CUSTOM'
}

export enum SUBSCRIPTION_TAB_NAMES {
  OVERVIEW = 'OVERVIEW',
  PLANS = 'PLANS',
  BILLING = 'BILLING'
}

export enum PLAN_UNIT {
  YEARLY = 'yearly',
  MONTHLY = 'monthly'
}

export enum SERVICES_CARDS {
  CURRENT_USAGE_CARD = 'CURRENT_USAGE_CARD',
  ACTUAL_USAGE_CARD = 'ACTUAL_USAGE_CARD',
  OVERUSE_USAGE_CARD = 'OVERUSE_USAGE_CARD',
  RECOMMENDATION_USAGE_CARD = 'RECOMMENDATION_USAGE_CARD'
}
