/* Generated by restful-react */

import React from 'react'
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from 'restful-react'

import { getConfig } from '../config'
export const SPEC_VERSION = '1.0.0'
export interface EvaluatedPolicy {
  deny_messages?: string[]
  output?: { [key: string]: any }
  policy?: LinkedPolicy
}

export interface Evaluation {
  account_id?: string
  created?: number
  id?: number
  org_id?: string
  project_id?: string
  summary?: EvaluationSummary
}

export interface EvaluationDetail {
  deny?: boolean
  policy_details?: EvaluatedPolicy[]
  policyset_id?: number
}

export interface EvaluationSummary {
  account_id?: string
  action?: string
  created?: number
  deny?: boolean
  details?: EvaluationDetail[]
  input?: { [key: string]: any }
  org_id?: string
  project_id?: string
  type?: string
}

export interface LinkedPolicy {
  account_id?: string
  created?: number
  id?: number
  name?: string
  org_id?: string
  project_id?: string
  rego?: string
  severity?: string
  updated?: number
}

export interface LinkedPolicyInput {
  severity?: string
}

export interface Policy {
  account_id?: string
  created?: number
  id?: number
  name?: string
  org_id?: string
  project_id?: string
  rego?: string
  updated?: number
}

export interface PolicyInput {
  name?: string
  rego?: string
}

export interface PolicySet {
  account_id?: string
  action?: string
  created?: number
  enabled?: boolean
  id?: number
  name?: string
  org_id?: string
  project_id?: string
  type?: string
  updated?: number
}

export interface PolicySetInput {
  action?: string
  enabled?: boolean
  name?: string
  type?: string
}

export interface PolicySetWithLinkedPolicies {
  account_id?: string
  action?: string
  created?: number
  enabled?: boolean
  id?: number
  name?: string
  org_id?: string
  policies?: LinkedPolicy[]
  project_id?: string
  type?: string
  updated?: number
}

export interface Token {
  access_token?: string
  uri?: string
}

export interface User {
  admin?: boolean
  authed?: number
  company?: string
  created?: number
  email?: string
  id?: number
  name?: string
  updated?: number
}

export interface UserInput {
  admin?: boolean
  company?: string
  email?: string
  name?: string
  password?: string
}

export type PolicyInputRequestBody = PolicyInput

export type PolicySetInputRequestBody = PolicySetInput

export type UserInputRequestBody = UserInput

export type EvaluateRawInputRequestBody = string

export type LoginRequestBody = void

export type AuthResponse = Token[]

export type EvaluateByIdsResponse = Evaluation

export type EvaluateByTypeResponse = Evaluation

export type EvaluateRawResponse = Evaluation

export type EvaluationResponse = Evaluation

export type EvaluationListResponse = Evaluation[]

export type PolicyResponse = Policy

export type PolicyListResponse = Policy[]

export type PolicysetResponse = PolicySetWithLinkedPolicies

export type PolicysetListResponse = PolicySet[]

export type UserResponse = User

export type UserListResponse = User[]

export interface EvaluateRawQueryParams {
  /**
   * The rego to be evaluated
   */
  rego?: string
}

export type EvaluateRawProps = Omit<
  MutateProps<PolicyResponse, unknown, EvaluateRawQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate arbitrary rego policies
 */
export const EvaluateRaw = (props: EvaluateRawProps) => (
  <Mutate<PolicyResponse, unknown, EvaluateRawQueryParams, EvaluateRawInputRequestBody, void>
    verb="POST"
    path={`/evaluate`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseEvaluateRawProps = Omit<
  UseMutateProps<PolicyResponse, unknown, EvaluateRawQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate arbitrary rego policies
 */
export const useEvaluateRaw = (props: UseEvaluateRawProps) =>
  useMutate<PolicyResponse, unknown, EvaluateRawQueryParams, EvaluateRawInputRequestBody, void>('POST', `/evaluate`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export interface EvaluateByIdsQueryParams {
  /**
   * Comma-separated list of policy set IDs
   */
  ids?: string
}

export type EvaluateByIdsProps = Omit<
  MutateProps<PolicyResponse, unknown, EvaluateByIdsQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate policy sets by policy set ids
 */
export const EvaluateByIds = (props: EvaluateByIdsProps) => (
  <Mutate<PolicyResponse, unknown, EvaluateByIdsQueryParams, EvaluateRawInputRequestBody, void>
    verb="POST"
    path={`/evaluate-by-ids`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseEvaluateByIdsProps = Omit<
  UseMutateProps<PolicyResponse, unknown, EvaluateByIdsQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate policy sets by policy set ids
 */
export const useEvaluateByIds = (props: UseEvaluateByIdsProps) =>
  useMutate<PolicyResponse, unknown, EvaluateByIdsQueryParams, EvaluateRawInputRequestBody, void>(
    'POST',
    `/evaluate-by-ids`,
    { base: getConfig('policy-mgmt'), ...props }
  )

export interface EvaluateByTypeQueryParams {
  /**
   * Harness account ID
   */
  accountIdentifier?: string
  /**
   * Harness org ID
   */
  orgIdentifier?: string
  /**
   * Harness project ID
   */
  projectIdentifier?: string
  /**
   * The type of entity that is under evaluation e.g. pipeline, environment
   */
  type?: string
  /**
   * The action performed on the entity that is under evaluation e.g. onrun, onsave
   */
  action?: string
}

export type EvaluateByTypeProps = Omit<
  MutateProps<PolicyResponse, unknown, EvaluateByTypeQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate policy sets by policy set type
 */
export const EvaluateByType = (props: EvaluateByTypeProps) => (
  <Mutate<PolicyResponse, unknown, EvaluateByTypeQueryParams, EvaluateRawInputRequestBody, void>
    verb="POST"
    path={`/evaluate-by-type`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseEvaluateByTypeProps = Omit<
  UseMutateProps<PolicyResponse, unknown, EvaluateByTypeQueryParams, EvaluateRawInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Evaluate policy sets by policy set type
 */
export const useEvaluateByType = (props: UseEvaluateByTypeProps) =>
  useMutate<PolicyResponse, unknown, EvaluateByTypeQueryParams, EvaluateRawInputRequestBody, void>(
    'POST',
    `/evaluate-by-type`,
    { base: getConfig('policy-mgmt'), ...props }
  )

export type GetEvaluationListProps = Omit<GetProps<EvaluationListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all evaluations
 */
export const GetEvaluationList = (props: GetEvaluationListProps) => (
  <Get<EvaluationListResponse, unknown, void, void> path={`/evaluations`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseGetEvaluationListProps = Omit<UseGetProps<EvaluationListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all evaluations
 */
export const useGetEvaluationList = (props: UseGetEvaluationListProps) =>
  useGet<EvaluationListResponse, unknown, void, void>(`/evaluations`, { base: getConfig('policy-mgmt'), ...props })

export type DeleteEvaluationProps = Omit<MutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the evaluation by ID
 */
export const DeleteEvaluation = (props: DeleteEvaluationProps) => (
  <Mutate<void, unknown, void, string, void>
    verb="DELETE"
    path={`/evaluations`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseDeleteEvaluationProps = Omit<UseMutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the evaluation by ID
 */
export const useDeleteEvaluation = (props: UseDeleteEvaluationProps) =>
  useMutate<void, unknown, void, string, void>('DELETE', `/evaluations`, { base: getConfig('policy-mgmt'), ...props })

export interface GetEvaluationPathParams {
  evaluation: string
}

export type GetEvaluationProps = Omit<GetProps<EvaluationResponse, unknown, void, GetEvaluationPathParams>, 'path'> &
  GetEvaluationPathParams

/**
 * Get the evaluation by ID
 */
export const GetEvaluation = ({ evaluation, ...props }: GetEvaluationProps) => (
  <Get<EvaluationResponse, unknown, void, GetEvaluationPathParams>
    path={`/evaluations/${evaluation}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseGetEvaluationProps = Omit<
  UseGetProps<EvaluationResponse, unknown, void, GetEvaluationPathParams>,
  'path'
> &
  GetEvaluationPathParams

/**
 * Get the evaluation by ID
 */
export const useGetEvaluation = ({ evaluation, ...props }: UseGetEvaluationProps) =>
  useGet<EvaluationResponse, unknown, void, GetEvaluationPathParams>(
    (paramsInPath: GetEvaluationPathParams) => `/evaluations/${paramsInPath.evaluation}`,
    { base: getConfig('policy-mgmt'), pathParams: { evaluation }, ...props }
  )

export type LoginProps = Omit<MutateProps<AuthResponse, unknown, void, LoginRequestBody, void>, 'path' | 'verb'>

/**
 * Return system health information
 */
export const Login = (props: LoginProps) => (
  <Mutate<AuthResponse, unknown, void, LoginRequestBody, void>
    verb="POST"
    path={`/login`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseLoginProps = Omit<UseMutateProps<AuthResponse, unknown, void, LoginRequestBody, void>, 'path' | 'verb'>

/**
 * Return system health information
 */
export const useLogin = (props: UseLoginProps) =>
  useMutate<AuthResponse, unknown, void, LoginRequestBody, void>('POST', `/login`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type GetPolicyListProps = Omit<GetProps<PolicyListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all policies
 */
export const GetPolicyList = (props: GetPolicyListProps) => (
  <Get<PolicyListResponse, unknown, void, void> path={`/policies`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseGetPolicyListProps = Omit<UseGetProps<PolicyListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all policies
 */
export const useGetPolicyList = (props: UseGetPolicyListProps) =>
  useGet<PolicyListResponse, unknown, void, void>(`/policies`, { base: getConfig('policy-mgmt'), ...props })

export type CreatePolicyProps = Omit<
  MutateProps<PolicyResponse, unknown, void, PolicyInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new policy
 */
export const CreatePolicy = (props: CreatePolicyProps) => (
  <Mutate<PolicyResponse, unknown, void, PolicyInputRequestBody, void>
    verb="POST"
    path={`/policies`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseCreatePolicyProps = Omit<
  UseMutateProps<PolicyResponse, unknown, void, PolicyInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new policy
 */
export const useCreatePolicy = (props: UseCreatePolicyProps) =>
  useMutate<PolicyResponse, unknown, void, PolicyInputRequestBody, void>('POST', `/policies`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type DeletePolicyProps = Omit<MutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the policy by ID
 */
export const DeletePolicy = (props: DeletePolicyProps) => (
  <Mutate<void, unknown, void, string, void>
    verb="DELETE"
    path={`/policies`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseDeletePolicyProps = Omit<UseMutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the policy by ID
 */
export const useDeletePolicy = (props: UseDeletePolicyProps) =>
  useMutate<void, unknown, void, string, void>('DELETE', `/policies`, { base: getConfig('policy-mgmt'), ...props })

export interface GetPolicyPathParams {
  policy: string
}

export type GetPolicyProps = Omit<GetProps<PolicyResponse, unknown, void, GetPolicyPathParams>, 'path'> &
  GetPolicyPathParams

/**
 * Get the policy by ID
 */
export const GetPolicy = ({ policy, ...props }: GetPolicyProps) => (
  <Get<PolicyResponse, unknown, void, GetPolicyPathParams>
    path={`/policies/${policy}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseGetPolicyProps = Omit<UseGetProps<PolicyResponse, unknown, void, GetPolicyPathParams>, 'path'> &
  GetPolicyPathParams

/**
 * Get the policy by ID
 */
export const useGetPolicy = ({ policy, ...props }: UseGetPolicyProps) =>
  useGet<PolicyResponse, unknown, void, GetPolicyPathParams>(
    (paramsInPath: GetPolicyPathParams) => `/policies/${paramsInPath.policy}`,
    { base: getConfig('policy-mgmt'), pathParams: { policy }, ...props }
  )

export interface UpdatePolicyPathParams {
  policy: string
}

export type UpdatePolicyProps = Omit<
  MutateProps<PolicyResponse, unknown, void, PolicyInputRequestBody, UpdatePolicyPathParams>,
  'path' | 'verb'
> &
  UpdatePolicyPathParams

/**
 * Update the policy by ID
 */
export const UpdatePolicy = ({ policy, ...props }: UpdatePolicyProps) => (
  <Mutate<PolicyResponse, unknown, void, PolicyInputRequestBody, UpdatePolicyPathParams>
    verb="PATCH"
    path={`/policies/${policy}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseUpdatePolicyProps = Omit<
  UseMutateProps<PolicyResponse, unknown, void, PolicyInputRequestBody, UpdatePolicyPathParams>,
  'path' | 'verb'
> &
  UpdatePolicyPathParams

/**
 * Update the policy by ID
 */
export const useUpdatePolicy = ({ policy, ...props }: UseUpdatePolicyProps) =>
  useMutate<PolicyResponse, unknown, void, PolicyInputRequestBody, UpdatePolicyPathParams>(
    'PATCH',
    (paramsInPath: UpdatePolicyPathParams) => `/policies/${paramsInPath.policy}`,
    { base: getConfig('policy-mgmt'), pathParams: { policy }, ...props }
  )

export interface GetPolicySetListQueryParams {
  accountIdentifier?: string
  orgIdentifier?: string
  projectIdentifier?: string
  type?: string
}

export type GetPolicySetListProps = Omit<
  GetProps<PolicysetListResponse, unknown, GetPolicySetListQueryParams, void>,
  'path'
>

/**
 * Get the list of all policysets
 */
export const GetPolicySetList = (props: GetPolicySetListProps) => (
  <Get<PolicysetListResponse, unknown, GetPolicySetListQueryParams, void>
    path={`/policysets`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseGetPolicySetListProps = Omit<
  UseGetProps<PolicysetListResponse, unknown, GetPolicySetListQueryParams, void>,
  'path'
>

/**
 * Get the list of all policysets
 */
export const useGetPolicySetList = (props: UseGetPolicySetListProps) =>
  useGet<PolicysetListResponse, unknown, GetPolicySetListQueryParams, void>(`/policysets`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type CreatePolicySetProps = Omit<
  MutateProps<PolicysetResponse, unknown, void, PolicySetInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new policyset
 */
export const CreatePolicySet = (props: CreatePolicySetProps) => (
  <Mutate<PolicysetResponse, unknown, void, PolicySetInputRequestBody, void>
    verb="POST"
    path={`/policysets`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseCreatePolicySetProps = Omit<
  UseMutateProps<PolicysetResponse, unknown, void, PolicySetInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new policyset
 */
export const useCreatePolicySet = (props: UseCreatePolicySetProps) =>
  useMutate<PolicysetResponse, unknown, void, PolicySetInputRequestBody, void>('POST', `/policysets`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type DeletePolicySetProps = Omit<MutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the policyset by ID
 */
export const DeletePolicySet = (props: DeletePolicySetProps) => (
  <Mutate<void, unknown, void, string, void>
    verb="DELETE"
    path={`/policysets`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseDeletePolicySetProps = Omit<UseMutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the policyset by ID
 */
export const useDeletePolicySet = (props: UseDeletePolicySetProps) =>
  useMutate<void, unknown, void, string, void>('DELETE', `/policysets`, { base: getConfig('policy-mgmt'), ...props })

export interface GetPolicySetPathParams {
  policyset: string
}

export type GetPolicySetProps = Omit<GetProps<PolicysetResponse, unknown, void, GetPolicySetPathParams>, 'path'> &
  GetPolicySetPathParams

/**
 * Get the policyset by ID
 */
export const GetPolicySet = ({ policyset, ...props }: GetPolicySetProps) => (
  <Get<PolicysetResponse, unknown, void, GetPolicySetPathParams>
    path={`/policysets/${policyset}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseGetPolicySetProps = Omit<UseGetProps<PolicysetResponse, unknown, void, GetPolicySetPathParams>, 'path'> &
  GetPolicySetPathParams

/**
 * Get the policyset by ID
 */
export const useGetPolicySet = ({ policyset, ...props }: UseGetPolicySetProps) =>
  useGet<PolicysetResponse, unknown, void, GetPolicySetPathParams>(
    (paramsInPath: GetPolicySetPathParams) => `/policysets/${paramsInPath.policyset}`,
    { base: getConfig('policy-mgmt'), pathParams: { policyset }, ...props }
  )

export interface UpdatePolicySetPathParams {
  policyset: string
}

export type UpdatePolicySetProps = Omit<
  MutateProps<PolicysetResponse, unknown, void, PolicySetInputRequestBody, UpdatePolicySetPathParams>,
  'path' | 'verb'
> &
  UpdatePolicySetPathParams

/**
 * Update the policyset by ID
 */
export const UpdatePolicySet = ({ policyset, ...props }: UpdatePolicySetProps) => (
  <Mutate<PolicysetResponse, unknown, void, PolicySetInputRequestBody, UpdatePolicySetPathParams>
    verb="PATCH"
    path={`/policysets/${policyset}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseUpdatePolicySetProps = Omit<
  UseMutateProps<PolicysetResponse, unknown, void, PolicySetInputRequestBody, UpdatePolicySetPathParams>,
  'path' | 'verb'
> &
  UpdatePolicySetPathParams

/**
 * Update the policyset by ID
 */
export const useUpdatePolicySet = ({ policyset, ...props }: UseUpdatePolicySetProps) =>
  useMutate<PolicysetResponse, unknown, void, PolicySetInputRequestBody, UpdatePolicySetPathParams>(
    'PATCH',
    (paramsInPath: UpdatePolicySetPathParams) => `/policysets/${paramsInPath.policyset}`,
    { base: getConfig('policy-mgmt'), pathParams: { policyset }, ...props }
  )

export type RegisterProps = Omit<MutateProps<AuthResponse, unknown, void, LoginRequestBody, void>, 'path' | 'verb'>

/**
 * Return system version information
 */
export const Register = (props: RegisterProps) => (
  <Mutate<AuthResponse, unknown, void, LoginRequestBody, void>
    verb="POST"
    path={`/register`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseRegisterProps = Omit<
  UseMutateProps<AuthResponse, unknown, void, LoginRequestBody, void>,
  'path' | 'verb'
>

/**
 * Return system version information
 */
export const useRegister = (props: UseRegisterProps) =>
  useMutate<AuthResponse, unknown, void, LoginRequestBody, void>('POST', `/register`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type HealthProps = Omit<GetProps<void, unknown, void, void>, 'path'>

/**
 * Return system health information
 */
export const Health = (props: HealthProps) => (
  <Get<void, unknown, void, void> path={`/system/health`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseHealthProps = Omit<UseGetProps<void, unknown, void, void>, 'path'>

/**
 * Return system health information
 */
export const useHealth = (props: UseHealthProps) =>
  useGet<void, unknown, void, void>(`/system/health`, { base: getConfig('policy-mgmt'), ...props })

export type GetCurrentUserProps = Omit<GetProps<UserResponse, unknown, void, void>, 'path'>

/**
 * Get the authenticated user.
 */
export const GetCurrentUser = (props: GetCurrentUserProps) => (
  <Get<UserResponse, unknown, void, void> path={`/user`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseGetCurrentUserProps = Omit<UseGetProps<UserResponse, unknown, void, void>, 'path'>

/**
 * Get the authenticated user.
 */
export const useGetCurrentUser = (props: UseGetCurrentUserProps) =>
  useGet<UserResponse, unknown, void, void>(`/user`, { base: getConfig('policy-mgmt'), ...props })

export type GetUserListProps = Omit<GetProps<UserListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all registered users.
 */
export const GetUserList = (props: GetUserListProps) => (
  <Get<UserListResponse, unknown, void, void> path={`/users`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseGetUserListProps = Omit<UseGetProps<UserListResponse, unknown, void, void>, 'path'>

/**
 * Get the list of all registered users.
 */
export const useGetUserList = (props: UseGetUserListProps) =>
  useGet<UserListResponse, unknown, void, void>(`/users`, { base: getConfig('policy-mgmt'), ...props })

export type CreateUserProps = Omit<
  MutateProps<UserResponse, unknown, void, UserInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new user.
 */
export const CreateUser = (props: CreateUserProps) => (
  <Mutate<UserResponse, unknown, void, UserInputRequestBody, void>
    verb="POST"
    path={`/users`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseCreateUserProps = Omit<
  UseMutateProps<UserResponse, unknown, void, UserInputRequestBody, void>,
  'path' | 'verb'
>

/**
 * Create a new user.
 */
export const useCreateUser = (props: UseCreateUserProps) =>
  useMutate<UserResponse, unknown, void, UserInputRequestBody, void>('POST', `/users`, {
    base: getConfig('policy-mgmt'),
    ...props
  })

export type DeleteUserProps = Omit<MutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the user with the matching email address.
 */
export const DeleteUser = (props: DeleteUserProps) => (
  <Mutate<void, unknown, void, string, void> verb="DELETE" path={`/users`} base={getConfig('policy-mgmt')} {...props} />
)

export type UseDeleteUserProps = Omit<UseMutateProps<void, unknown, void, string, void>, 'path' | 'verb'>

/**
 * Delete the user with the matching email address.
 */
export const useDeleteUser = (props: UseDeleteUserProps) =>
  useMutate<void, unknown, void, string, void>('DELETE', `/users`, { base: getConfig('policy-mgmt'), ...props })

export interface GetUserPathParams {
  user: string
}

export type GetUserProps = Omit<GetProps<UserResponse, unknown, void, GetUserPathParams>, 'path'> & GetUserPathParams

/**
 * Get the user with the matching email address.
 */
export const GetUser = ({ user, ...props }: GetUserProps) => (
  <Get<UserResponse, unknown, void, GetUserPathParams>
    path={`/users/${user}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseGetUserProps = Omit<UseGetProps<UserResponse, unknown, void, GetUserPathParams>, 'path'> &
  GetUserPathParams

/**
 * Get the user with the matching email address.
 */
export const useGetUser = ({ user, ...props }: UseGetUserProps) =>
  useGet<UserResponse, unknown, void, GetUserPathParams>(
    (paramsInPath: GetUserPathParams) => `/users/${paramsInPath.user}`,
    { base: getConfig('policy-mgmt'), pathParams: { user }, ...props }
  )

export interface UpdateUserPathParams {
  user: string
}

export type UpdateUserProps = Omit<
  MutateProps<UserResponse, unknown, void, UserInputRequestBody, UpdateUserPathParams>,
  'path' | 'verb'
> &
  UpdateUserPathParams

/**
 * Update the user with the matching email address.
 */
export const UpdateUser = ({ user, ...props }: UpdateUserProps) => (
  <Mutate<UserResponse, unknown, void, UserInputRequestBody, UpdateUserPathParams>
    verb="PATCH"
    path={`/users/${user}`}
    base={getConfig('policy-mgmt')}
    {...props}
  />
)

export type UseUpdateUserProps = Omit<
  UseMutateProps<UserResponse, unknown, void, UserInputRequestBody, UpdateUserPathParams>,
  'path' | 'verb'
> &
  UpdateUserPathParams

/**
 * Update the user with the matching email address.
 */
export const useUpdateUser = ({ user, ...props }: UseUpdateUserProps) =>
  useMutate<UserResponse, unknown, void, UserInputRequestBody, UpdateUserPathParams>(
    'PATCH',
    (paramsInPath: UpdateUserPathParams) => `/users/${paramsInPath.user}`,
    { base: getConfig('policy-mgmt'), pathParams: { user }, ...props }
  )
