/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps } from "restful-react";

import { getConfig } from "../config";
export const SPEC_VERSION = "1.0.0"; 
export interface GithubMember {
  id?: number;
  name?: string;
  login?: string;
  avatar_url?: string;
}

export type AllGithubUsersResponse = GithubMember[];

export type AllGithubUsersProps = Omit<GetProps<AllGithubUsersResponse, void, void, void>, "path">;

/**
 * Gets allGithubUsers
 * 
 * allGithubUsers
 */
export const AllGithubUsers = (props: AllGithubUsersProps) => (
  <Get<AllGithubUsersResponse, void, void, void>
    path={`/github/all_users`}
    base={getConfig("asaasin/api")}
    
    {...props}
  />
);

export type UseAllGithubUsersProps = Omit<UseGetProps<AllGithubUsersResponse, void, void, void>, "path">;

/**
 * Gets allGithubUsers
 * 
 * allGithubUsers
 */
export const useAllGithubUsers = (props: UseAllGithubUsersProps) => useGet<AllGithubUsersResponse, void, void, void>(`/github/all_users`, { base:getConfig("asaasin/api"),  ...props });

